@startuml Entity_Relationship_Diagram

'Alt + D para mostrar diagrama entidad relacion utilizando "plantuml"

'|##############################################################|
'|###                        Entities                        ###|
'|##############################################################|

entity "Jugador" as Jugador {
  *id_jugador : uuid
  --
  nombre : string
  edad: int
  apellido : string
  email : string
  rankingPaddle : int
  rankingTennis : int
}

entity "Administrador" as Admin {
  *id_administrador : uuid
  --
  nombre : string
  email : string
  contraseña : string
}

entity "Torneo" as Torneo {
  *id_torneo : uuid
  --
  nombre : string
  deporte: string
  duo : bool  
  fecha_inicio : date
  fecha_fin : date
  ubicación : string
  estado : string
}


entity "Partido" as Partido {
  *id_partido : uuid
  --
  fecha : date
  hora : time
  fase : string
  resultado : string
  -- Foreign Keys --
  id_torneo : uuid
  id_ganador : uuid
}


'|###################################################################|
'|###                        Linking Table                        ###|
'|###################################################################|

entity "Participacion" as Participacion {
  -- Foreign Keys --
  *id_jugador : uuid
  *id_torneo : uuid
  --
  ranking_en_torneo : int
}

entity "Partido_Jugador" as PJ {
  -- Foreign Keys --
  *id_partido : uuid
  *id_jugador : uuid
  --
  equipo : bool
}



'|##################################################################|
'|###                        Relationship                        ###|
'|##################################################################|


Torneo ||--o{ Partido
Torneo ||--o{ Participacion

Jugador ||--o{ Participacion
Jugador ||--o{ PJ

Partido ||--o{ PJ

'|###########################################################|
'|###                        Notes                        ###|
'|###########################################################|
note left of Torneo::estado
  Valores posibles:
  - 'pendiente'
  - 'en curso'
  - 'finalizado'
end note

@enduml
